;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-WORD-begin
	evil-backward-char
	evil-backward-word-begin
	evil-change
	evil-delete
	evil-digit-argument-or-evil-beginning-of-line
	evil-end-of-line
	evil-execute-in-emacs-state
	evil-first-non-blank
	evil-forward-WORD-begin
	evil-forward-WORD-end
	evil-forward-char
	evil-forward-char-or-extend
	evil-forward-word-begin
	evil-forward-word-end
	evil-insert
	evil-mode
	evil-next-line
	evil-normal-state
	evil-open-above
	evil-open-below
	evil-paste-after
	evil-previous-line
	keyboard-escape-quit
	move-beginning-of-line-or-text
	))

(setq mc/cmds-to-run-once
      '(
	))
