(add-to-list 'load-path (expand-file-name "popwin-el" user-emacs-directory)) 
(add-to-list 'load-path (expand-file-name "popwin-el/misc" user-emacs-directory)) 
(require 'popwin)
(popwin-mode 1)
(global-set-key (kbd "C-S-z") popwin:keymap)
(when (boundp 'popwin:special-display-config)
  (loop for CONFIG in
	'(("*Quail Completions* " :noselect t)
	  ("^\\*.*makey-key.*\\*$" :regexp t)
	  ("^\\*helm.*\\*$" :regexp t :height 30))
	do (add-to-list 'popwin:special-display-config CONFIG))
  popwin:special-display-config)
